name: Build OpenVicProject
description: Build OpenVicProject with provided options.
inputs:
  target:
    description: Build target (editor, template_release, template_debug).
    default: "template_release"
  platform:
    description: Target platform.
    required: false
  sconsflags:
    description: Flags to add to scons
    default: ""
  scons-cache:
    description: The scons cache path.
    default: "${{ github.workspace }}/.scons-cache/"
  scons-cache-limit:
    description: The scons cache size limit.
    # actions/cache has 10 GiB limit, and GitHub runners have a 14 GiB disk.
    # Limit to 7 GiB to avoid having the extracted cache fill the disk.
    default: "7168"
  bin-dir:
    description: The binary directory to seek files in.
    default: "bin/"
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: sh
      env:
        SCONSFLAGS: ${{ inputs.sconsflags }}
        SCONS_CACHE: ${{ inputs.scons-cache }}
        SCONS_CACHE_LIMIT: ${{ inputs.scons-cache-limit }}
      run: |
        echo "Building with flags:" platform=${{ inputs.platform }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}
        scons platform=${{ inputs.platform }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}
        ls -l ${{ inputs.bin-dir }}
